import type { Metadata } from "next";
import { ArrowUpRight, CheckCircle2, CircleDashed } from "lucide-react";
import { getCatalog } from "@/lib/data";

export const metadata: Metadata = { title: "官方来源与核验状态" };
export default function SourcesPage() {
  const { sources, vendors } = getCatalog();
  return <div className="shell py-12 md:py-16"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="eyebrow">SOURCE REGISTRY</div><h1 className="mt-3 text-5xl font-black tracking-[-.06em] md:text-7xl">来源与核验</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#5f5b54]">{sources.length} 条证据。每 4 小时扫描脚本会检查链接与关键正文；“已核验”表示人工确认过支持字段。</p></div><div className="paper-card p-4 text-xs"><div className="flex items-center gap-2 font-black"><span className="status-dot" /> 每 4 小时 UTC :17</div><div className="mt-2 text-[#6f6b63]">检测到变化后自动创建审核 Issue</div></div></div><div className="mt-12 border-t border-black">{sources.map((source, index) => { const vendor = vendors.find(v => v.id === source.vendorId); return <a key={source.id} href={source.url} target="_blank" rel="noreferrer" className="group grid gap-3 border-b hairline py-4 hover:bg-white/40 md:grid-cols-[44px_190px_1fr_130px_28px] md:items-center"><span className="mono text-[10px] text-[#6f6b63]">{String(index + 1).padStart(2, "0")}</span><div><div className="text-xs font-black">{vendor?.name ?? "Independent"}</div><div className="mt-1 text-[9px] uppercase text-[#6f6b63]">{source.kind}</div></div><div><div className="text-sm font-black">{source.title}</div><div className="mt-1 text-[10px] text-[#6f6b63]">{source.supports.join(" · ")}</div></div><div className="flex items-center gap-2 text-[10px] font-bold">{source.status === "verified" ? <CheckCircle2 size={13} className="text-[#168b4f]" /> : <CircleDashed size={13} className="text-[#b18200]" />}{source.verifiedAt}</div><ArrowUpRight size={15} className="group-hover:text-[var(--blue)]" /></a>; })}</div></div>;
}
